# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

resources:
  containers:
  - container: seleniumhub
    image: selenium/hub:latest
    ports:
    - 4444:4444
  - container: seleniumnode
    image: selenium/node-chrome:latest
    options: "-e HUB_HOST=seleniumhub"

pool:
  vmImage: 'ubuntu-latest'

services:
  seleniumhub: seleniumhub
  seleniumnode: seleniumnode

steps:
- script: |
    curl http://localhost:4444/grid/console

# steps:
# - task: Cache@2
#   inputs:
#     key: 'maven | "$(Agent.OS)" | **/pom.xml'
#     restoreKeys: |
#       maven | "$(Agent.OS)"
#       maven
#     path: $(MAVEN_CACHE_FOLDER)
#   displayName: Cache Maven local repo
# - task: Maven@3
#   inputs:
#     mavenPomFile: 'pom.xml'
#     mavenOptions: '-Xmx3072m'
#     javaHomeOption: 'JDKVersion'
#     jdkVersionOption: '1.8'
#     jdkArchitectureOption: 'x64'
#     publishJUnitResults: true
#     testResultsFiles: '**/surefire-reports/TEST-*.xml'
#     goals: 'clean verify allure:report -P grid -DsuiteXmlFile=smoke.suite.xml'


    
